# Generated by Django 4.2.1 on 2023-05-14 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('product', 'machine')},
        ),
    ]
