# Generated by Django 4.2.1 on 2023-05-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_variant_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('waiting', 'Waiting')], default='idle', max_length=10),
        ),
    ]
