# Generated by Django 4.2.1 on 2023-05-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_machine_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('idle', 'idle'), ('waiting', 'waiting')], default='idle', max_length=10),
        ),
    ]
